# Describes the format for available services for bibliotheek_be

get_song_bpm:
  description: >
    Get the BPM of a song
  fields:
    song:
      description: >
        Name and artist of the song
      example: Eminem Loose yourself
      